SELECT TOP (1000) [continent]
      ,[location]
      ,[date]
      ,[population]
      ,[new_vaccinations]
      ,[Rollin_people_vaccinated]
  FROM [CovidPortfolioProject].[dbo].[PercentPopulationVaccinated]
